using System.Runtime.CompilerServices;
using Saga.Core.Abstractions;

namespace Saga.Infrastructure.Ai;

/// <summary>
/// Stand-in used when AzureOpenAI:Endpoint is not configured, so the whole artifact loop
/// runs offline (and in tests) without spending tokens. Streams a canned markdown response.
/// </summary>
public class FakeAiService : IAiService
{
    public async IAsyncEnumerable<AiStreamEvent> StreamAsync(AiRequest request,
        [EnumeratorCancellation] CancellationToken ct = default)
    {
        var text = $"""
            *(Generated by the offline stand-in AI — configure AzureOpenAI:Endpoint to use the real models.)*

            ## What the client is asking for
            A placeholder response for a **{request.Tier}** model request. The real model would analyse
            the working context ({request.SystemPrompt.Length + request.Messages.Sum(m => m.Content.Length)} characters of prompt) and respond here.

            ## Central themes
            - Theme one from the client material
            - Theme two from the client material

            ## Ambiguities and risks
            - This is canned text, not a real analysis.
            """;

        foreach (var chunk in text.Split(' '))
        {
            ct.ThrowIfCancellationRequested();
            yield return new AiStreamEvent.Delta(chunk + " ");
            await Task.Delay(10, ct);
        }
        yield return new AiStreamEvent.Completed(1000, 200, "fake-model");
    }
}
