using System.Runtime.CompilerServices;
using Saga.Core.Abstractions;

namespace Saga.Infrastructure.Ai;

/// <summary>
/// Stand-in used when AzureOpenAI:Endpoint is not configured, so the whole artifact loop
/// runs offline (and in tests) without spending tokens. Streams a canned markdown response.
/// </summary>
public class FakeAiService : IAiService
{
    public async IAsyncEnumerable<AiStreamEvent> StreamAsync(AiRequest request,
        [EnumeratorCancellation] CancellationToken ct = default)
    {
        // JSON-contract prompts (e.g. requirements extraction) get canned JSON back.
        if (request.SystemPrompt.Contains("Return ONLY a JSON array"))
        {
            var json = """
                [
                  {"text": "The offer must be submitted no later than the stated deadline.", "type": "Practical", "interpretation": "Hard submission deadline.", "howAddressed": "Plan internal review to finish well before the deadline."},
                  {"text": "The supplier must document experience with comparable assignments.", "type": "Mandatory", "interpretation": "References from similar projects are required.", "howAddressed": "Include two or three anonymised case references."},
                  {"text": "The solution will be evaluated on quality of the proposed approach.", "type": "Criterion", "interpretation": "The methodology section carries evaluation weight.", "howAddressed": "Make the approach concrete, phased and tied to the client's goals."}
                ]
                """;
            yield return new AiStreamEvent.Delta(json);
            yield return new AiStreamEvent.Completed(500, 150, "fake-model");
            yield break;
        }

        var text = $"""
            *(Generated by the offline stand-in AI — configure AzureOpenAI:Endpoint to use the real models.)*

            ## What the client is asking for
            A placeholder response for a **{request.Tier}** model request. The real model would analyse
            the working context ({request.SystemPrompt.Length + request.Messages.Sum(m => m.Content.Length)} characters of prompt) and respond here.

            ## Central themes
            - Theme one from the client material
            - Theme two from the client material

            ## Ambiguities and risks
            - This is canned text, not a real analysis.
            """;

        foreach (var chunk in text.Split(' '))
        {
            ct.ThrowIfCancellationRequested();
            yield return new AiStreamEvent.Delta(chunk + " ");
            await Task.Delay(10, ct);
        }
        yield return new AiStreamEvent.Completed(1000, 200, "fake-model");
    }
}
